import { EntityManager } from "../../../entity-manager";
import { DatabaseEvents } from "../../../entity-manager/types/database-events";
import { CustomClass } from "../../../entity-manager/types/metadata-type";

interface HandleDataParams {
	data: Array<any>;
	entityManager: EntityManager;
	entity: CustomClass;
	autoGenerateEvents: Array<DatabaseEvents>;
}

export const beforeFormatDataArray = <Entity>({
	data,
	entity,
	entityManager,
	autoGenerateEvents,
}: HandleDataParams) => {
	const dataWithAutoGeneratedFields = data.map(d =>
		entityManager.autoGenerateEntityToDatabase<Entity>({
			events: autoGenerateEvents,
			entity,
			data: d,
		}),
	);

	const dataInDatabaseFormat = dataWithAutoGeneratedFields.map(d =>
		entityManager.convertEntityToDatabase({
			data: d,
			entity,
		}),
	);

	return dataInDatabaseFormat as Array<any>;
};
