import { PrimaryGeneratedColumnOptions } from "../types/column-options";
import { getDatabaseName } from "./helpers/get-database-name";
import { getType } from "./helpers/get-type";
import { MetadataUtil } from "../../utils/metadata-util";
import { getStrategy } from "./helpers/get-strategy";

export type PrimaryGeneratedColumnStrategy = "uuid";

// eslint-disable-next-line @typescript-eslint/naming-convention
export const PrimaryGeneratedColumn = (
	strategyOrOptions?:
		| PrimaryGeneratedColumnOptions
		| PrimaryGeneratedColumnStrategy,
) => {
	return (entityPrototype: any, propertyName: string) => {
		const { databaseName, isNameAlreadyFormatted } = getDatabaseName({
			propertyName,
			strategyOrOptions,
		});
		const type = getType({
			entityPrototype,
			propertyName,
		});
		const strategy = getStrategy({
			strategyOrOptions,
			entityPrototype,
			propertyName,
		});

		MetadataUtil.addColumnMetadataToEntity({
			entity: entityPrototype.constructor,
			metadata: {
				name: propertyName,
				databaseName,
				isNameAlreadyFormatted,
				isAutoGenerated: true,
				autoGenerate: strategy,
				autoGenerationType: "ENTITY_TO_DATABASE",
				type,
				primary: true,
				extras: (strategyOrOptions as PrimaryGeneratedColumnOptions)?.extras,
			},
		});
	};
};
