import { EntityManager } from "../../../../entity-manager";
import { CustomClass } from "../../../../entity-manager/types/metadata-type";

interface HandleDataParams {
	data: any;
	entityManager: EntityManager<any, any>;
	entity: CustomClass;
}

export const handleData = ({
	data,
	entity,
	entityManager,
}: HandleDataParams) => {
	const dataWithAutoGeneratedFields =
		entityManager.autoGenerateEntityToDatabase({
			events: ["update"],
			entity,
			data,
		});

	const dataInDatabaseFormat = entityManager.convertEntityToDatabase({
		data: dataWithAutoGeneratedFields,
		entity,
	});

	return dataInDatabaseFormat;
};
