import { DateColumnOptions } from "./types/column-options";
import { getOptions } from "./helpers/get-options";
import { makeColumnDecorator } from "./helpers/make-column-decorator";

// eslint-disable-next-line @typescript-eslint/naming-convention
export const UpdateDateColumn = (options?: DateColumnOptions) => {
	const { extras, name } = getOptions<DateColumnOptions>(options);

	return makeColumnDecorator({
		metadata: {
			extras,
			databaseName: name,
			isAutoGenerated: true,
			autoGenerationType: "ENTITY_TO_DATABASE",
			autoGenerateOnlyOnEvents: ["save", "update"],
			autoGenerate: "date",
		},
		acceptedTypes: ["string", "number", "date"],
	});
};
