import { ColumnMetadata } from "../../../types/column-metadata";

export const shouldAutoGenerate = (columnMetadata: ColumnMetadata) =>
	columnMetadata.isAutoGenerated &&
	columnMetadata.autoGenerationType === "ENTITY_TO_DATABASE" &&
	columnMetadata.autoGenerate;
