import { EntityManager } from "../../../../entity-manager";
import { CustomClass } from "../../../../entity-manager/types/metadata-type";

interface HandleDataArrayParams<Entity> {
	data: Array<Entity>;
	entityManager: EntityManager;
	entity: CustomClass;
}

export const formatDataArray = <Entity>({
	data,
	entity,
	entityManager,
}: HandleDataArrayParams<Entity>) => {
	const dataWithAutoGeneratedFields = data.map(d =>
		entityManager.autoGenerateEntityToDatabase<Entity>({
			events: ["save"],
			entity,
			data: d,
		}),
	);

	const dataInDatabaseFormat = dataWithAutoGeneratedFields.map(d =>
		entityManager.convertEntityToDatabase({
			data: d,
			entity,
		}),
	);

	return dataInDatabaseFormat;
};
