import { DateColumnOptions } from "../types/column-options";
import { getOptions } from "../helpers/get-options";
import { makeColumnDecorator } from "./helpers/make-column-decorator";

// eslint-disable-next-line @typescript-eslint/naming-convention
export const DeleteDateColumn = <ColumnExtraMetadata = any>(
	options?: DateColumnOptions<ColumnExtraMetadata>,
) => {
	const { name, ...metadata } =
		getOptions<DateColumnOptions<ColumnExtraMetadata>>(options);

	return makeColumnDecorator({
		metadata: {
			...metadata,
			databaseName: name,
			isAutoGenerated: true,
			autoGenerationType: "ENTITY_TO_DATABASE",
			autoGenerateOnlyOnEvents: ["delete"],
			autoGenerate: "date",
		},
		acceptedTypes: ["string", "number", "date"],
	});
};
