import { EntityManager } from "../../../../entity-manager";
import { CustomClass } from "../../../../entity-manager/types/metadata-type";

interface HandleDataArrayParams {
	data: Array<any>;
	entityManager: EntityManager<any, any>;
	entity: CustomClass;
}

export const formatDataArray = ({
	data,
	entity,
	entityManager,
}: HandleDataArrayParams) => {
	const dataWithAutoGeneratedFields = data.map(d =>
		entityManager.autoGenerateEntityToDatabase({
			events: ["save", "update"],
			entity,
			data: d,
		}),
	);

	const dataInDatabaseFormat = dataWithAutoGeneratedFields.map(d =>
		entityManager.convertEntityToDatabase({
			data: d,
			entity,
		}),
	);

	return dataInDatabaseFormat;
};
